services:
 backend:
  image: gugu-shop
  build: .
  ports:
  - "8082:80"
  volumes:
  - .:/code
 redis:
  image: redis
 sql-server-db:
  container_name: sql-server-db
  ports:
  - "1434:1433"
  build: .