services:
 backend:
  image: gugu_shop
  build: .
  ports:
  - "8082:80"
  volumes:
  - .:/code
 redis:
  image: redis
 sql-server-db:
  container_name: sql_server_db
  ports:
  - "1433:1433"
  build: .